from flask import Blueprint, redirect
from templates import LANDING_CSS
from auth import me

landing_bp = Blueprint('landing', __name__)


@landing_bp.route('/')
def landing():
    if me():
        return redirect('/dashboard')

    html = (
        '<!DOCTYPE html><html lang="ru"><head>'
        '<meta charset="UTF-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>A/B Testing Pro &mdash; Больше продаж на Озоне</title>'
        '<style>' + LANDING_CSS + '</style>'
        '</head><body>'

        # Навигация
        '<nav class="lnav">'
        '<div class="lnav-logo">A/B Testing Pro</div>'
        '<div class="lnav-links">'
        '<a href="#how">Как работает</a>'
        '<a href="#features">Возможности</a>'
        '<a href="#pricing">Тарифы</a>'
        '<a href="/login">Войти</a>'
        '<a href="/register" class="lnav-cta">Начать бесплатно</a>'
        '</div></nav>'

        # Hero
        '<section class="hero">'
        '<div class="hero-bg"><div class="blob b1"></div><div class="blob b2"></div><div class="blob b3"></div></div>'
        '<div style="position:relative;z-index:1">'
        '<div class="hero-badge">&#127381; Попробуйте бесплатно — 2 теста в подарок при регистрации</div>'
        '<h1>Ваши конкуренты уже<br>тестируют. <span>А вы?</span></h1>'
        '<p class="hero-sub">Автоматически проверяйте какие фотографии товаров продают лучше. До 10 вариантов одновременно &mdash; без Excel, без ручной работы.</p>'
        '<div class="hero-btns">'
        '<a href="/register" class="btn-hero btn-main">Получить 2 теста бесплатно &rarr;</a>'
        '<a href="#how" class="btn-hero btn-ghost">Как это работает?</a>'
        '</div>'
        '<div class="hero-stat">'
        '<div class="stat-item"><div class="stat-n">+34%</div><div class="stat-l">средний рост конверсии</div></div>'
        '<div class="stat-item"><div class="stat-n">до 10</div><div class="stat-l">вариантов фото в тесте</div></div>'
        '<div class="stat-item"><div class="stat-n">2 теста</div><div class="stat-l">бесплатно при регистрации</div></div>'
        '</div></div></section>'

        # Проблема
        '<section class="problem">'
        '<div class="section-tag">Знакомо?</div>'
        '<h2 class="section-h">Почему 90% продавцов<br>теряют деньги каждый день</h2>'
        '<p class="section-sub">Большинство продавцов выбирают фото «на глазок» и никогда не узнают, сколько продаж они потеряли из-за одной неудачной картинки.</p>'
        '<div class="problem-cards">'
        '<div class="prob-card"><div class="prob-icon">&#128064;</div><h3>Выбирают фото интуитивно</h3><p>«Мне кажется это красиво» — не аргумент. Покупатели думают иначе.</p></div>'
        '<div class="prob-card"><div class="prob-icon">&#128202;</div><h3>Нет данных для решений</h3><p>Без теста невозможно знать, какое фото реально приносит больше кликов и продаж.</p></div>'
        '<div class="prob-card"><div class="prob-icon">&#9200;</div><h3>Нет времени делать вручную</h3><p>Менять фото, записывать статистику, считать конверсии — часы работы каждую неделю.</p></div>'
        '</div></section>'

        # Как работает
        '<section class="how" id="how"><div class="how-inner">'
        '<div class="how-title"><div class="section-tag">Просто и быстро</div><h2 class="section-h">Три шага до роста продаж</h2></div>'
        '<div class="steps">'
        '<div class="step"><div class="step-num">01</div><h3>Подключите магазин</h3><p>Введите API-ключ Озона. Сервис автоматически получит доступ к вашим товарам. Занимает 2 минуты.</p></div>'
        '<div class="step"><div class="step-num">02</div><h3>Загрузите варианты фото</h3><p>От 2 до 10 вариантов первого фото. Сервис начнёт показывать их покупателям по очереди.</p></div>'
        '<div class="step"><div class="step-num">03</div><h3>Получайте результаты</h3><p>Сервис определит победителя по CTR и конверсии и автоматически применит лучшее фото.</p></div>'
        '</div></div></section>'

        # Возможности
        '<section class="features" id="features">'
        '<div class="feat-title"><div class="section-tag">Возможности</div><h2 class="section-h">Всё что нужно для роста</h2></div>'
        '<div class="feat-grid">'
        '<div class="feat-card"><div class="feat-ic">&#127922;</div><h3>До 10 вариантов в одном тесте</h3><p>Мультивариантное тестирование. Тестируйте разные ракурсы, фоны, инфографику.</p></div>'
        '<div class="feat-card"><div class="feat-ic">&#128200;</div><h3>Автоматическая ротация</h3><p>Сервис сам меняет фото и выбирает лучший вариант — без ручной работы каждый день.</p></div>'
        '<div class="feat-card"><div class="feat-ic">&#128269;</div><h3>Реальная аналитика</h3><p>Просмотры, клики, CTR, продажи, конверсия по каждому варианту в одном месте.</p></div>'
        '<div class="feat-card"><div class="feat-ic">&#128737;</div><h3>Безопасно и надёжно</h3><p>Ключи хранятся в зашифрованном виде. Работаем только через официальный API Озона.</p></div>'
        '<div class="feat-card"><div class="feat-ic">&#9889;</div><h3>Быстрый старт</h3><p>Первый тест за 5 минут. Никаких сложных настроек — подключили и работаете.</p></div>'
        '<div class="feat-card"><div class="feat-ic">&#128276;</div><h3>Уведомления о результатах</h3><p>Получайте сообщения когда тест завершён и найден победитель.</p></div>'
        '</div></section>'

        # Тариф
        '<section class="pricing" id="pricing"><div class="pricing-inner">'
        '<div class="section-tag" style="display:block;text-align:center">Прозрачные условия</div>'
        '<h2 class="section-h">Начните бесплатно</h2>'
        '<div class="price-card">'
        '<div class="price-badge">&#127381; Специальное предложение</div>'
        '<div class="price-badge">&#127381; При регистрации — 2 теста бесплатно</div>''<div class="price-tag">500 &#8381; <span>/ 1 тест</span></div>'
        '<p class="price-sub">При регистрации вы получаете <strong>1 000 токенов бесплатно</strong> — это 2 теста. Затем платите только за использование.</p>'
        '<ul class="price-features">'
        '<li><span class="check-ic">&#127381;</span> <strong>1 000 токенов бесплатно</strong> при регистрации (2 теста)</li>''<li><span class="check-ic">&#10003;</span> Далее: 1 тест = 500 токенов = 500&#8381;</li>'
        '<li><span class="check-ic">&#10003;</span> До 10 вариантов фото в одном тесте</li>'
        '<li><span class="check-ic">&#10003;</span> Автоматическая ротация и аналитика</li>'
        '<li><span class="check-ic">&#10003;</span> Токены зачисляются мгновенно после оплаты</li>'
        '<li><span class="check-ic">&#10003;</span> Поддержка 7 дней в неделю</li>'
        '</ul>'
        '<a href="/register" class="btn-hero btn-main" style="width:100%;justify-content:center;display:flex">Получить 2 теста бесплатно &rarr;</a>'
        '</div></div></section>'

        # CTA
        '<section class="cta-section">'
        '<div class="cta-bg"></div>'
        '<div style="position:relative;z-index:1">'
        '<h2>Хватит терять деньги<br>на неправильных фото</h2>'
        '<p style="color:#888;font-size:1.1rem;margin:1.5rem auto 2.5rem;max-width:500px">'
        'Пока вы читаете это — ваши конкуренты уже тестируют. Начните прямо сейчас, это бесплатно.</p>'
        '<a href="/register" class="btn-hero btn-main">Получить 2 теста бесплатно &rarr;</a>'
        '</div></section>'

        # Футер
        '<footer class="footer">'
        '<div style="max-width:1100px;margin:0 auto;padding:2rem 1rem;'
        'display:flex;justify-content:space-between;flex-wrap:wrap;gap:2rem">'
        '<div>'
        '<div style="font-weight:700;margin-bottom:.5rem">A/B Testing Pro</div>'
        '<div style="font-size:.82rem;color:#aaa">ИП Клюева Наталья Анатольевна</div>'
        '<div style="font-size:.82rem;color:#aaa;margin-top:.3rem">'
        '&#169; 2025 A/B Testing Pro</div></div>'
        '<div>'
        '<div style="font-weight:600;margin-bottom:.75rem;font-size:.9rem">Политики и соглашения</div>'
        '<div style="display:flex;flex-direction:column;gap:.4rem">'
        '<a href="/terms" style="color:#aaa;font-size:.85rem">Пользовательское соглашение</a>'
        '<a href="/payment-policy" style="color:#aaa;font-size:.85rem">Политика оплаты и возврата</a>'
        '<a href="/privacy" style="color:#aaa;font-size:.85rem">Политика конфиденциальности</a>'
        '</div></div>'
        '<div>'
        '<div style="font-weight:600;margin-bottom:.75rem;font-size:.9rem">Контакты</div>'
        '<div style="display:flex;flex-direction:column;gap:.4rem">'
        '<a href="mailto:attilainfo@yandex.ru" style="color:#aaa;font-size:.85rem">attilainfo@yandex.ru</a>'
        '<a href="/contacts" style="color:#aaa;font-size:.85rem">Реквизиты</a>'
        '<a href="/login" style="color:#aaa;font-size:.85rem">Войти</a>'
        '<a href="/register" style="color:#ff4d6d;font-size:.85rem">Регистрация</a>'
        '</div></div>'
        '</div>'
        '</footer>'

        '</body></html>'
    )
    return html

@landing_bp.route('/terms')
def terms():
    html = (
        '<!DOCTYPE html><html lang="ru"><head>'
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Публичная оферта — A/B Testing Pro</title>'
        '<style>' + 'body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;''background:#f8f9fa;color:#1a1a2e;line-height:1.7}''.wrap{max-width:820px;margin:0 auto;padding:2rem 1rem}''h1{font-size:1.8rem;font-weight:700;margin-bottom:.5rem;color:#1a1a2e}''h2{font-size:1.15rem;font-weight:700;margin:2rem 0 .75rem;color:#333;border-bottom:2px solid #f0f2f5;padding-bottom:.4rem}''h3{font-size:1rem;font-weight:700;margin:1.2rem 0 .5rem;color:#444}''p,li{font-size:.92rem;color:#444;margin-bottom:.6rem}''ul,ol{padding-left:1.5rem;margin-bottom:1rem}''.meta{font-size:.85rem;color:#888;margin-bottom:2rem;padding:.5rem .75rem;background:#f0f2f5;border-radius:6px;display:inline-block}''.back{display:inline-block;margin-bottom:1.5rem;color:#667eea;font-size:.9rem;text-decoration:none}''.foot{font-size:.82rem;color:#aaa;margin-top:2rem;padding-top:1rem;border-top:1px solid #e0e0e0}''.foot a{color:#667eea}' + '</style></head><body><div class="wrap">'
        '<a href="/" class="back">&#8592; На главную</a>'
        '<h1>Публичная оферта на оказание услуг</h1>'
        '<span class="meta">Дата публикации: 1 мая 2025 г. &nbsp;·&nbsp; Редакция 1.0</span>'

        '<h2>1. Общие положения</h2>'
        '<p>Настоящий документ является публичной офертой индивидуального предпринимателя '
        'Клюевой Натальи Анатольевны (ОГРНИП 322527500044708, ИНН 360402011440), '
        'именуемого далее «Исполнитель», и содержит все существенные условия договора '
        'на оказание услуг сервиса A/B Testing Pro (далее — Сервис).</p>'
        '<p>Акцептом настоящей оферты является регистрация на сайте и/или оплата услуг. '
        'С момента акцепта договор считается заключённым на условиях настоящей оферты.</p>'
        '<p>Условия могут быть изменены Исполнителем без предварительного уведомления. '
        'Актуальная редакция всегда доступна по адресу: '
        '<a href="https://mpservice-production.up.railway.app/terms" style="color:#667eea">'
        'mpservice-production.up.railway.app/terms</a></p>'

        '<h2>2. Термины и определения</h2>'
        '<p><strong>Сервис</strong> — программный комплекс A/B Testing Pro, доступный по адресу '
        'mpservice-production.up.railway.app, предназначенный для автоматического '
        'тестирования изображений товаров на маркетплейсе Ozon.</p>'
        '<p><strong>Пользователь (Заказчик)</strong> — физическое или юридическое лицо, '
        'зарегистрировавшееся в Сервисе и принявшее условия настоящей оферты.</p>'
        '<p><strong>Токены</strong> — внутренние единицы Сервиса, используемые для оплаты услуг '
        'внутри системы. 1 токен = 1 рубль.</p>'
        '<p><strong>Тест</strong> — автоматизированная процедура сравнения вариантов изображений '
        'товара с целью определения наиболее эффективного.</p>'

        '<h2>3. Предмет договора</h2>'
        '<p>Исполнитель предоставляет Заказчику доступ к Сервису на условиях '
        'неисключительной лицензии. Сервис предоставляется «как есть» (as is).</p>'
        '<p>Исполнитель не несёт ответственности за перебои в работе API маркетплейсов, '
        'изменения в их функциональности, а также за коммерческие результаты использования Сервиса.</p>'

        '<h2>4. Стоимость и порядок оплаты</h2>'
        '<ul>'
        '<li>1 токен = 1 рубль</li>'
        '<li>Минимальное пополнение баланса: 500 рублей = 500 токенов</li>'
        '<li>Стоимость запуска одного A/B теста: 500 токенов (может быть изменена Исполнителем)</li>'
        '<li>Оплата осуществляется через платёжный сервис ЮКасса банковскими картами VISA, '
        'MasterCard, МИР</li>'
        '<li>Токены зачисляются на баланс автоматически после подтверждения оплаты</li>'
        '<li>Фискальный чек направляется на email Заказчика в соответствии с ФЗ-54</li>'
        '<li>Оплата производится на условиях 100% предоплаты</li>'
        '</ul>'

        '<h2>5. Порядок оказания услуг</h2>'
        '<ul>'
        '<li>Доступ к Сервису предоставляется после регистрации и пополнения баланса токенов</li>'
        '<li>Токены списываются в момент запуска теста и не возвращаются вне зависимости от '
        'результата теста или причин его остановки</li>'
        '<li>Текущие активные тесты продолжают работу до завершения даже при нулевом балансе</li>'
        '<li>Исполнитель вправе изменить стоимость услуг, разместив новые условия на сайте</li>'
        '</ul>'

        '<h2>6. Возврат денежных средств</h2>'
        '<p>Возврат неиспользованных токенов (не задействованных для запуска тестов) возможен '
        'по письменному запросу на email attilainfo@yandex.ru в течение 14 дней с момента '
        'пополнения баланса.</p>'
        '<p>Возврат осуществляется на те же реквизиты, с которых была произведена оплата, '
        'в течение 10 рабочих дней.</p>'
        '<p>Токены, использованные для запуска тестов, возврату не подлежат.</p>'

        '<h2>7. Ответственность сторон</h2>'
        '<p>Исполнитель не несёт ответственности за:</p>'
        '<ul>'
        '<li>Перебои в работе API Ozon и других маркетплейсов</li>'
        '<li>Изменения в политике и функциональности маркетплейсов</li>'
        '<li>Коммерческие результаты использования Сервиса</li>'
        '<li>Действия третьих лиц, включая платёжные системы</li>'
        '</ul>'
        '<p>Совокупная ответственность Исполнителя ограничена суммой последнего платежа '
        'Заказчика.</p>'

        '<h2>8. Конфиденциальность</h2>'
        '<p>Исполнитель обязуется не передавать данные Заказчика третьим лицам, за исключением '
        'случаев, предусмотренных законодательством РФ или необходимых для исполнения '
        'настоящего договора (платёжные системы). API-ключи маркетплейсов хранятся '
        'в зашифрованном виде.</p>'

        '<h2>9. Форс-мажор</h2>'
        '<p>Стороны освобождаются от ответственности за неисполнение обязательств при '
        'наступлении обстоятельств непреодолимой силы (стихийные бедствия, действия '
        'государственных органов, перебои в работе сетей связи и т.д.).</p>'

        '<h2>10. Прочие условия</h2>'
        '<p>К отношениям Сторон применяется законодательство Российской Федерации. '
        'Все споры решаются путём переговоров, при недостижении согласия — '
        'в суде по месту нахождения Исполнителя.</p>'
        '<p>Если какое-либо положение настоящего договора окажется недействительным, '
        'остальные положения сохраняют силу.</p>'

        '<h2>11. Реквизиты исполнителя</h2>'
        '<p>' + 'ИП Клюева Наталья Анатольевна<br>''ИНН: 360402011440, ОГРНИП: 322527500044708<br>''Email: <a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a><br>''Телефон: +7 986 755-48-93' + '</p>'
        + '<p class="foot">'+'<a href="/terms">Публичная оферта</a> &nbsp;·&nbsp; '+'<a href="/privacy">Политика конфиденциальности</a> &nbsp;·&nbsp; '+'<a href="/payment-policy">Политика оплаты и возврата</a> &nbsp;·&nbsp; '+'<a href="/contacts">Контакты</a> &nbsp;·&nbsp; '+'&#169; 2025 A/B Testing Pro</p>' +
        '</div></body></html>'
    )
    return html


@landing_bp.route('/privacy')
def privacy():
    html = (
        '<!DOCTYPE html><html lang="ru"><head>'
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Политика конфиденциальности — A/B Testing Pro</title>'
        '<style>' + 'body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;''background:#f8f9fa;color:#1a1a2e;line-height:1.7}''.wrap{max-width:820px;margin:0 auto;padding:2rem 1rem}''h1{font-size:1.8rem;font-weight:700;margin-bottom:.5rem;color:#1a1a2e}''h2{font-size:1.15rem;font-weight:700;margin:2rem 0 .75rem;color:#333;border-bottom:2px solid #f0f2f5;padding-bottom:.4rem}''h3{font-size:1rem;font-weight:700;margin:1.2rem 0 .5rem;color:#444}''p,li{font-size:.92rem;color:#444;margin-bottom:.6rem}''ul,ol{padding-left:1.5rem;margin-bottom:1rem}''.meta{font-size:.85rem;color:#888;margin-bottom:2rem;padding:.5rem .75rem;background:#f0f2f5;border-radius:6px;display:inline-block}''.back{display:inline-block;margin-bottom:1.5rem;color:#667eea;font-size:.9rem;text-decoration:none}''.foot{font-size:.82rem;color:#aaa;margin-top:2rem;padding-top:1rem;border-top:1px solid #e0e0e0}''.foot a{color:#667eea}' + '</style></head><body><div class="wrap">'
        '<a href="/" class="back">&#8592; На главную</a>'
        '<h1>Политика в отношении обработки персональных данных</h1>'
        '<span class="meta">Дата публикации: 1 мая 2025 г. &nbsp;·&nbsp; Редакция 1.0</span>'

        '<h2>1. Общие положения</h2>'
        '<p>Настоящая политика составлена в соответствии с требованиями Федерального закона '
        'от 27.07.2006 № 152-ФЗ «О персональных данных» и определяет порядок обработки '
        'персональных данных пользователей сервиса A/B Testing Pro.</p>'
        '<p>1.1. Оператор ставит своей важнейшей целью соблюдение прав и свобод человека '
        'при обработке персональных данных, в том числе защиты прав на неприкосновенность '
        'частной жизни.</p>'
        '<p>1.2. Оператор персональных данных: ИП Клюева Наталья Анатольевна, '
        'ОГРНИП 322527500044708, ИНН 360402011440 (далее — Оператор).</p>'
        '<p>1.3. Настоящая Политика применяется ко всей информации, которую Оператор может '
        'получить о посетителях сайта mpservice-production.up.railway.app.</p>'

        '<h2>2. Основные понятия</h2>'
        '<p><strong>Персональные данные</strong> — любая информация, относящаяся прямо или '
        'косвенно к определённому Пользователю.</p>'
        '<p><strong>Обработка персональных данных</strong> — любое действие с персональными '
        'данными: сбор, запись, хранение, уточнение, извлечение, использование, передача, '
        'блокирование, удаление, уничтожение.</p>'
        '<p><strong>Пользователь</strong> — любой посетитель сайта '
        'mpservice-production.up.railway.app.</p>'

        '<h2>3. Какие данные мы обрабатываем</h2>'
        '<p>3.1. Оператор обрабатывает следующие персональные данные Пользователя:</p>'
        '<ul>'
        '<li>Имя и фамилия — указываются при регистрации</li>'
        '<li>Адрес электронной почты — для входа и уведомлений</li>'
        '<li>API-ключи маркетплейсов — для подключения магазина (хранятся в зашифрованном виде)</li>'
        '<li>История действий в Сервисе — тесты, транзакции, статистика</li>'
        '<li>Технические данные — IP-адрес, тип браузера, дата и время обращений</li>'
        '</ul>'
        '<p>3.2. Обработка специальных категорий персональных данных (расовая принадлежность, '
        'политические взгляды, религиозные убеждения и т.п.) Оператором не осуществляется.</p>'
        '<p>3.3. Оператор обрабатывает персональные данные Пользователя только в случае их '
        'самостоятельного заполнения через формы на сайте.</p>'

        '<h2>4. Цели обработки персональных данных</h2>'
        '<ul>'
        '<li>Идентификация Пользователя и предоставление доступа к Сервису</li>'
        '<li>Исполнение договора (публичной оферты)</li>'
        '<li>Обработка платежей и ведение финансовой отчётности в соответствии с ФЗ-54</li>'
        '<li>Направление уведомлений о результатах тестов и состоянии аккаунта</li>'
        '<li>Информирование об изменениях в работе Сервиса</li>'
        '<li>Улучшение качества работы Сервиса</li>'
        '<li>Соблюдение требований законодательства РФ</li>'
        '</ul>'

        '<h2>5. Правовые основания обработки</h2>'
        '<p>Обработка персональных данных осуществляется на основании:</p>'
        '<ul>'
        '<li>Согласия субъекта персональных данных (ст. 6, ч. 1, п. 1 ФЗ-152)</li>'
        '<li>Исполнения договора, стороной которого является субъект (ст. 6, ч. 1, п. 5 ФЗ-152)</li>'
        '<li>Федерального закона от 27.07.2006 № 149-ФЗ «Об информации, информационных '
        'технологиях и о защите информации»</li>'
        '<li>Соблюдения требований законодательства РФ (ст. 6, ч. 1, п. 2 ФЗ-152)</li>'
        '</ul>'

        '<h2>6. Основные права и обязанности Оператора</h2>'
        '<p>6.1. Оператор обязан:</p>'
        '<ul>'
        '<li>Предоставлять субъекту информацию об обработке его персональных данных по запросу</li>'
        '<li>Организовывать обработку данных в порядке, установленном законодательством РФ</li>'
        '<li>Принимать меры по защите персональных данных от неправомерного доступа</li>'
        '<li>Прекратить обработку и уничтожить данные в случаях, предусмотренных ФЗ-152</li>'
        '</ul>'

        '<h2>7. Права субъекта персональных данных</h2>'
        '<p>7.1. Пользователь вправе:</p>'
        '<ul>'
        '<li>Получить информацию об обработке своих персональных данных</li>'
        '<li>Требовать уточнения, блокирования или уничтожения своих данных</li>'
        '<li>Отозвать согласие на обработку персональных данных</li>'
        '<li>Обжаловать действия Оператора в Роскомнадзор</li>'
        '</ul>'
        '<p>Для реализации прав направьте запрос: '
        '<a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a> '
        'с пометкой «Персональные данные».</p>'

        '<h2>8. Передача данных третьим лицам</h2>'
        '<p>8.1. Персональные данные Пользователя не будут переданы третьим лицам, '
        'за исключением:</p>'
        '<ul>'
        '<li><strong>ЮКасса (НКО «ЮМани»)</strong> — для обработки платежей. Передаются '
        'только данные, необходимые для проведения оплаты</li>'
        '<li><strong>По требованию закона</strong> — при обязательном запросе уполномоченных '
        'органов государственной власти РФ</li>'
        '</ul>'
        '<p>8.2. Вся информация, собираемая сторонними сервисами (платёжными системами), '
        'хранится и обрабатывается ими в соответствии с их политиками конфиденциальности.</p>'

        '<h2>9. Хранение и защита данных</h2>'
        '<ul>'
        '<li>Данные хранятся на защищённых серверах (Railway, США) с шифрованием соединения</li>'
        '<li>Пароли хранятся в хэшированном виде (bcrypt) и не могут быть восстановлены</li>'
        '<li>API-ключи маркетплейсов хранятся в зашифрованном виде</li>'
        '<li>Срок хранения — в течение действия аккаунта и 3 года после его удаления; '
        'финансовые документы — 5 лет согласно требованиям законодательства РФ</li>'
        '<li>Обрабатываемые данные уничтожаются по достижении целей обработки</li>'
        '</ul>'

        '<h2>10. Cookies</h2>'
        '<p>Сайт использует cookies только для хранения сессии авторизации. '
        'Сторонние аналитические и рекламные сервисы не используются. '
        'Вы можете отключить cookies в настройках браузера, однако это нарушит работу '
        'авторизации.</p>'

        '<h2>11. Трансграничная передача</h2>'
        '<p>Данные хранятся на серверах в США (Railway Inc.). Оператор убедился в наличии '
        'надлежащей защиты прав субъектов персональных данных в указанном государстве.</p>'

        '<h2>12. Заключительные положения</h2>'
        '<p>12.1. Пользователь может получить разъяснения по вопросам обработки персональных '
        'данных, обратившись на email: attilainfo@yandex.ru.</p>'
        '<p>12.2. Политика действует бессрочно до замены новой версией. В документе отражаются '
        'все изменения в политике обработки данных.</p>'
        '<p>12.3. Актуальная версия: '
        '<a href="https://mpservice-production.up.railway.app/privacy" style="color:#667eea">'
        'mpservice-production.up.railway.app/privacy</a></p>'

        '<h2>Реквизиты оператора</h2>'
        '<p>' + 'ИП Клюева Наталья Анатольевна<br>''ИНН: 360402011440, ОГРНИП: 322527500044708<br>''Email: <a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a><br>''Телефон: +7 986 755-48-93' + '</p>'
        + '<p class="foot">'+'<a href="/terms">Публичная оферта</a> &nbsp;·&nbsp; '+'<a href="/privacy">Политика конфиденциальности</a> &nbsp;·&nbsp; '+'<a href="/payment-policy">Политика оплаты и возврата</a> &nbsp;·&nbsp; '+'<a href="/contacts">Контакты</a> &nbsp;·&nbsp; '+'&#169; 2025 A/B Testing Pro</p>' +
        '</div></body></html>'
    )
    return html


@landing_bp.route('/payment-policy')
def payment_policy():
    html = (
        '<!DOCTYPE html><html lang="ru"><head>'
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Политика оплаты и возврата — A/B Testing Pro</title>'
        '<style>' + 'body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;''background:#f8f9fa;color:#1a1a2e;line-height:1.7}''.wrap{max-width:820px;margin:0 auto;padding:2rem 1rem}''h1{font-size:1.8rem;font-weight:700;margin-bottom:.5rem;color:#1a1a2e}''h2{font-size:1.15rem;font-weight:700;margin:2rem 0 .75rem;color:#333;border-bottom:2px solid #f0f2f5;padding-bottom:.4rem}''h3{font-size:1rem;font-weight:700;margin:1.2rem 0 .5rem;color:#444}''p,li{font-size:.92rem;color:#444;margin-bottom:.6rem}''ul,ol{padding-left:1.5rem;margin-bottom:1rem}''.meta{font-size:.85rem;color:#888;margin-bottom:2rem;padding:.5rem .75rem;background:#f0f2f5;border-radius:6px;display:inline-block}''.back{display:inline-block;margin-bottom:1.5rem;color:#667eea;font-size:.9rem;text-decoration:none}''.foot{font-size:.82rem;color:#aaa;margin-top:2rem;padding-top:1rem;border-top:1px solid #e0e0e0}''.foot a{color:#667eea}' + '</style></head><body><div class="wrap">'
        '<a href="/" class="back">&#8592; На главную</a>'
        '<h1>Политика оплаты и возврата</h1>'
        '<span class="meta">Дата публикации: 1 мая 2025 г. &nbsp;·&nbsp; Редакция 1.0</span>'

        '<h2>Особенности оплаты</h2>'
        '<p>К оплате принимаются банковские карты: VISA, MasterCard, МИР.</p>'
        '<p>При оплате банковской картой обработка платежа происходит на защищённой странице '
        'платёжного сервиса ЮКасса, где необходимо ввести:</p>'
        '<ul>'
        '<li>Номер карты</li>'
        '<li>Срок действия карты</li>'
        '<li>Имя держателя карты</li>'
        '<li>CVC2/CVV2 код</li>'
        '</ul>'
        '<p>Если карта подключена к 3D-Secure — вы будете перенаправлены на страницу банка '
        'для дополнительной аутентификации.</p>'
        '<p>Конфиденциальные данные вашей карты не передаются и не хранятся на серверах '
        'A/B Testing Pro — их обработка производится исключительно на стороне ЮКассы.</p>'

        '<h2>Доставка / активация</h2>'
        '<p>Фактически оплачивается пополнение токенового баланса в личном кабинете. '
        'Активация происходит автоматически после получения подтверждения оплаты от '
        'платёжной системы, как правило — моментально.</p>'
        '<p>Токены зачисляются на баланс аккаунта Пользователя и могут быть использованы '
        'для запуска A/B тестов.</p>'

        '<h2>Возврат денежных средств</h2>'
        '<p>Пользователь вправе запросить возврат неиспользованных токенов при соблюдении '
        'следующих условий:</p>'
        '<ul>'
        '<li>Запрос направлен в течение 14 дней с момента пополнения баланса</li>'
        '<li>Токены не были использованы для запуска тестов</li>'
        '</ul>'
        '<p>Для запроса возврата направьте письмо на email '
        '<a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a> '
        'с темой «Возврат средств» и укажите:</p>'
        '<ul>'
        '<li>Email аккаунта</li>'
        '<li>Дату и сумму пополнения</li>'
        '<li>Причину возврата</li>'
        '</ul>'
        '<p>Возврат осуществляется на те же реквизиты, с которых была произведена оплата, '
        'в течение 10 рабочих дней с момента одобрения заявки.</p>'
        '<p><strong>Токены, использованные для запуска тестов, возврату не подлежат</strong> — '
        'независимо от результата теста или причин его остановки.</p>'

        '<h2>Вопросы по оплате</h2>'
        '<p>По всем вопросам, связанным с оплатой, обращайтесь: '
        '<a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a></p>'

        '<h2>Реквизиты</h2>'
        '<p>' + 'ИП Клюева Наталья Анатольевна<br>''ИНН: 360402011440, ОГРНИП: 322527500044708<br>''Email: <a href="mailto:attilainfo@yandex.ru" style="color:#667eea">attilainfo@yandex.ru</a><br>''Телефон: +7 986 755-48-93' + '</p>'
        + '<p class="foot">'+'<a href="/terms">Публичная оферта</a> &nbsp;·&nbsp; '+'<a href="/privacy">Политика конфиденциальности</a> &nbsp;·&nbsp; '+'<a href="/payment-policy">Политика оплаты и возврата</a> &nbsp;·&nbsp; '+'<a href="/contacts">Контакты</a> &nbsp;·&nbsp; '+'&#169; 2025 A/B Testing Pro</p>' +
        '</div></body></html>'
    )
    return html


# ── Контакты ───────────────────────────────────────────────────────────────

@landing_bp.route('/contacts')
def contacts():
    html = (
        '<!DOCTYPE html><html lang="ru"><head>'
        '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        '<title>Контакты — A/B Testing Pro</title>'
        '<style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;'
        'background:#f8f9fa;color:#1a1a2e;line-height:1.7}'
        '.wrap{max-width:700px;margin:0 auto;padding:2rem 1rem}'
        'h1{font-size:1.8rem;font-weight:700;margin-bottom:2rem}'
        '.card{background:#fff;border-radius:12px;padding:1.5rem;'
        'box-shadow:0 2px 8px rgba(0,0,0,.07);margin-bottom:1rem}'
        '.row{display:flex;gap:1rem;align-items:flex-start;padding:.6rem 0;'
        'border-bottom:1px solid #f0f2f5}'
        '.row:last-child{border-bottom:none}'
        '.ic{font-size:1.3rem;min-width:2rem}'
        '.lbl{font-size:.82rem;color:#888;margin-bottom:.2rem}'
        '.val{font-size:.95rem;font-weight:600;color:#1a1a2e}'
        'a.val{color:#667eea}'
        '.back{display:inline-block;margin-bottom:1.5rem;color:#667eea;font-size:.9rem;text-decoration:none}'
        '</style></head><body><div class="wrap">'
        '<a href="/" class="back">&#8592; На главную</a>'
        '<h1>&#128222; Контакты и реквизиты</h1>'
        '<div class="card">'
        '<div class="row"><div class="ic">&#128100;</div><div>'
        '<div class="lbl">Организация</div><div class="val">ИП Клюева Наталья Анатольевна</div>'
        '</div></div>'
        '<div class="row"><div class="ic">&#128196;</div><div>'
        '<div class="lbl">ИНН</div><div class="val">360402011440</div></div></div>'
        '<div class="row"><div class="ic">&#128196;</div><div>'
        '<div class="lbl">ОГРНИП</div><div class="val">322527500044708</div></div></div>'
        '<div class="row"><div class="ic">&#128231;</div><div>'
        '<div class="lbl">Email</div>'
        '<a href="mailto:attilainfo@yandex.ru" class="val">attilainfo@yandex.ru</a>'
        '</div></div>'
        '<div class="row"><div class="ic">&#128222;</div><div>'
        '<div class="lbl">Телефон</div>'
        '<a href="tel:+79867554893" class="val">+7 986 755-48-93</a></div></div>'
        '<div class="row"><div class="ic">&#127760;</div><div>'
        '<div class="lbl">Сайт</div>'
        '<a href="https://mpservice-production.up.railway.app" class="val">'
        'mpservice-production.up.railway.app</a></div></div>'
        '</div>'
        '<div class="card">'
        '<div class="row"><div class="ic">&#9203;</div><div>'
        '<div class="lbl">Время ответа</div><div class="val">В течение 24 часов в рабочие дни</div>'
        '</div></div>'
        '<div class="row"><div class="ic">&#128230;</div><div>'
        '<div class="lbl">По вопросам оплаты и возврата</div>'
        '<a href="mailto:attilainfo@yandex.ru" class="val">attilainfo@yandex.ru</a>'
        '</div></div></div>'
        '<p style="font-size:.82rem;color:#aaa;margin-top:1rem">'
        '<a href="/terms" style="color:#667eea">Оферта</a> &nbsp;·&nbsp; '
        '<a href="/privacy" style="color:#667eea">Конфиденциальность</a> &nbsp;·&nbsp; '
        '<a href="/payment-policy" style="color:#667eea">Оплата и возврат</a> &nbsp;·&nbsp; '
        '&#169; 2025 A/B Testing Pro</p>'
        '</div></body></html>'
    )
    return html
